### PR TITLE
Fixes OSX build

### LINKED ISSUE #803: MRPT runs on MacOS10.14
Emmm... I have tried to build mrpt on MacOS10.14, but some requirements can not be fullfilled.

Is there any solutions for running MRPT on MacOS? Or does anyone try to fix it? I would like to join this fixed work.

### PR DESCRIPTION
**Pull request by jolting**
closes #803

### CODE REVIEW

File: libs/obs/include/mrpt/obs/CObservationVelodyneScan.h [hunk 1]
```diff
@@ -200,7 +200,7 @@ class CObservationVelodyneScan : public CObservation
 		/** The list of point indices (in x,y,z,...) generated for each laserID
 		 * (ring number). Generated only if `generatePointsForLaserID`=true in
 		 * `TGeneratePointCloudParameters`*/
-		std::vector<std::vector<std::size_t>> pointsForLaserID;
+		std::vector<std::vector<uint64_t>> pointsForLaserID;
```
Comment (jolting) [inline libs/obs/include/mrpt/obs/CObservationVelodyneScan.h]: @jlblancoc This one fixes a 32-bit/64-bit compatibility issue, but files saved on 32-bit machines will be broken.

**Comment by jlblancoc** [comment]
Great! It seems it now builds on your newly-setup MacOS config in CircleCI :+1: 
Merge yourself when you are happy with the changes. 

PS: The deprecation of glBegin()/glEnd() seems like it will require a lot of work... (sigh)
